version: "3.8"
services:
  redis:
    image: "redis:alpine"

  video-tele:
    image: node:14-alpine
    volumes:
      - .:/app
    command: |
      sh -c '
      cd /app
      npm install
      node server.js
      '
    ports:
      - "1338:1338"